# Generated by Django 3.0.3 on 2020-04-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200323_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
    ]
