# Generated by Django 3.0.3 on 2020-04-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=244),
        ),
        migrations.AddField(
            model_name='profile',
            name='goalweight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
