# Generated by Django 3.0.3 on 2020-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200413_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goalweight',
            field=models.IntegerField(default=0, help_text='In kgs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=0, help_text='In cms'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=0, help_text='In kgs'),
        ),
    ]
