# Generated by Django 3.0.3 on 2020-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200420_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
    ]
