# Generated by Django 2.2 on 2020-05-18 16:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200518_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='meal_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=list, size=None),
        ),
    ]
