# Generated by Django 2.2 on 2020-05-18 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200518_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='meal_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
    ]
